// data.js  – with highlighting hint
export const csvData = /* csv */ String.raw`




id,description
CostumedPlay,"Root concept of costumed roleplay/dress‑up"

/* Depth 1 -------------------------------------------------------------- */
CostumedPlay.Community,"Fandom‑based gatherings"
CostumedPlay.Performance,"Costumed performance"
CostumedPlay.Activism,"Costumes for protests or statements"
CostumedPlay.Illegal,"Costumed play crossing legal boundaries"
CostumedPlay.PersonalExpression,"For personal creativity"
CostumedPlay.Hobbyism,"Pure hobby‑based costuming"
CostumedPlay.Political,"Costuming for direct political statements"
CostumedPlay.Escapism,"Escape from daily life"
CostumedPlay.Charity,"Philanthropic costuming"
CostumedPlay.Professionalism,"Costumed play as a career"

/* Depth 2 -------------------------------------------------------------- */
CostumedPlay.Community.Furry,"Fans wearing 'fursuits'"
CostumedPlay.Community.Juggalos,"Face‑painted fans of ICP"
CostumedPlay.Community.SteampunkEnthusiasts,"Neo‑Victorian steam aesthetics"
CostumedPlay.Community.ConventionCosplayers,"Fans who cosplay pop‑culture characters"

CostumedPlay.Performance.DragQueens,"Exaggerated female personas"
CostumedPlay.Performance.LuchaLibreWrestlers,"Masked Mexican wrestlers"
CostumedPlay.Performance.AnimegaoKigurumi,"Oversized anime‑style masks"

CostumedPlay.Activism.GuerrillaGirls,"Feminist artists in gorilla masks"
CostumedPlay.Activism.PussyRiot,"Russian feminist punks in balaclavas"
CostumedPlay.Activism.BlackBloc,"Protesters in all‑black"
CostumedPlay.Activism.SiegedSec,"'Gay Furry Hackers'"
CostumedPlay.Activism.Hacktivism,"Masked hacking protest groups"

CostumedPlay.Illegal.BlackHatCosplayers,"Cosplay crossing legal lines"
CostumedPlay.Illegal.Hacktivism,"Another hacking umbrella"
CostumedPlay.Illegal.GraffitiCrews,"Tagging & street art in costume"

CostumedPlay.Hobbyism.HistoricalReenactment,"Groups recreating past eras"
CostumedPlay.Escapism.LARPers,"Live‑action role‑players"
CostumedPlay.Escapism.RenaissanceFaireEnthusiasts,"Fans of Renaissance faires"
CostumedPlay.Charity.501stLegion,"Star Wars costumers for charity"
CostumedPlay.Charity.MagicWheelchair,"Non‑profit building wheelchair costumes"
CostumedPlay.Professionalism.ThemeParkCharacters,"Paid performers at major parks"
CostumedPlay.Professionalism.ProCosplayers,"Earning income from cosplay"

/* Depth 3 examples ----------------------------------------------------- */
CostumedPlay.Community.Furry.MidwestFurFest,"Large furry convention in Chicago"
CostumedPlay.Community.Juggalos.GatheringOfTheJuggalos,"Annual ICP festival"
CostumedPlay.Community.SteampunkEnthusiasts.SteampunkSalons,"Local meetups"
CostumedPlay.Activism.Hacktivism.Anonymous,"Online hacktivists (Guy Fawkes)"
CostumedPlay.Activism.Hacktivism.LulzSec,"Historic lulzy hacker group"
CostumedPlay.Illegal.Hacktivism.TheDarkWebCrew,"(Fictional) deep hacking ring"
CostumedPlay.Escapism.LARPers.DystopiaRising,"Post‑apocalyptic LARP"
CostumedPlay.Hobbyism.HistoricalReenactment.NapoleonicWars,"Napoleonic reenactors"
CostumedPlay.Hobbyism.HistoricalReenactment.SCA,"Society for Creative Anachronism"
CostumedPlay.Professionalism.ThemeParkCharacters.DisneyFaceCharacters,"Princesses & heroes"
CostumedPlay.Professionalism.ThemeParkCharacters.DisneyFurs,"Disney park fursuits"

/* Single‑depth leaves -------------------------------------------------- */
CostumedPlay.Community.Juggalos.InsaneClownPosse,"The rap duo central to Juggalos"
CostumedPlay.Community.Furry.SonicFox,"Furry esports champion"
CostumedPlay.PersonalExpression.LolitaFashion,"Frilly Victorian style"
CostumedPlay.PersonalExpression.PupPlayers,"Kink subculture with canine role‑play"

/* MEDIA TYPE hubs (depth 4) ------------------------------------------- */
CostumedPlay.Community.ConventionCosplayers.Anime,"Catch‑all node for anime franchises"
CostumedPlay.Community.ConventionCosplayers.Manga,"Catch‑all node for manga series"
CostumedPlay.Community.ConventionCosplayers.VideoGames,"Catch‑all node for video‑game franchises"
CostumedPlay.Community.ConventionCosplayers.Comics,"Catch‑all node for comic universes"
CostumedPlay.Community.ConventionCosplayers.Series,"Catch‑all node for live‑action series"
CostumedPlay.Community.ConventionCosplayers.Movies,"Catch‑all node for film franchises"

/* ================ 1) ANIME (40 leaves) ============================ */
CostumedPlay.Community.ConventionCosplayers.Anime.Naruto,"Ninja saga"
CostumedPlay.Community.ConventionCosplayers.Anime.OnePiece,"Pirate epic"
CostumedPlay.Community.ConventionCosplayers.Anime.Bleach,"Soul reapers vs Hollows"
CostumedPlay.Community.ConventionCosplayers.Anime.DragonBall,"Martial‑arts aliens"
CostumedPlay.Community.ConventionCosplayers.Anime.AttackOnTitan,"Humans vs titans"
CostumedPlay.Community.ConventionCosplayers.Anime.MyHeroAcademia,"Young heroes‑in‑training"
CostumedPlay.Community.ConventionCosplayers.Anime.DemonSlayer,"Samurai‑like demon hunters"
CostumedPlay.Community.ConventionCosplayers.Anime.JujutsuKaisen,"Exorcists vs curses"
CostumedPlay.Community.ConventionCosplayers.Anime.FullmetalAlchemist,"Alchemy brothers"
CostumedPlay.Community.ConventionCosplayers.Anime.DeathNote,"Killer notebook"
CostumedPlay.Community.ConventionCosplayers.Anime.TokyoGhoul,"Ghouls in Tokyo"
CostumedPlay.Community.ConventionCosplayers.Anime.FairyTail,"Wizard guild"
CostumedPlay.Community.ConventionCosplayers.Anime.Inuyasha,"Feudal demon fantasy"
CostumedPlay.Community.ConventionCosplayers.Anime.SailorMoon,"Magical‑girl warriors"
CostumedPlay.Community.ConventionCosplayers.Anime.HunterXHunter,"Nen adventures"
CostumedPlay.Community.ConventionCosplayers.Anime.JoJosBizarreAdventure,"Generational saga"
CostumedPlay.Community.ConventionCosplayers.Anime.NeonGenesisEvangelion,"Mecha vs Angels"
CostumedPlay.Community.ConventionCosplayers.Anime.CodeGeass,"Mecha & mind‑control dystopia"
CostumedPlay.Community.ConventionCosplayers.Anime.SwordArtOnline,"Trapped in VR MMO"
CostumedPlay.Community.ConventionCosplayers.Anime.ReZero,"Death‑loop isekai"
CostumedPlay.Community.ConventionCosplayers.Anime.Konosuba,"Comedy isekai"
CostumedPlay.Community.ConventionCosplayers.Anime.Gintama,"Samurai parody"
CostumedPlay.Community.ConventionCosplayers.Anime.Haikyuu,"High‑school volleyball"
CostumedPlay.Community.ConventionCosplayers.Anime.KurokoNoBasket,"Basketball with super plays"
CostumedPlay.Community.ConventionCosplayers.Anime.BlackClover,"Magic knights"
CostumedPlay.Community.ConventionCosplayers.Anime.DrStone,"Science after petrification"
CostumedPlay.Community.ConventionCosplayers.Anime.FireForce,"Pyrokinetic firefighters"
CostumedPlay.Community.ConventionCosplayers.Anime.ThePromisedNeverland,"Orphans & dark secret"
CostumedPlay.Community.ConventionCosplayers.Anime.ChainsawMan,"Chainsaw‑demon hybrid"
CostumedPlay.Community.ConventionCosplayers.Anime.SpyxFamily,"Spy + assassin + telepath"
CostumedPlay.Community.ConventionCosplayers.Anime.FruitsBasket,"Zodiac‑curse drama"
CostumedPlay.Community.ConventionCosplayers.Anime.Berserk,"Dark medieval fantasy"
CostumedPlay.Community.ConventionCosplayers.Anime.Claymore,"Half‑human warriors"
CostumedPlay.Community.ConventionCosplayers.Anime.CowboyBebop,"Space bounty hunters"
CostumedPlay.Community.ConventionCosplayers.Anime.LupinIII,"Gentleman thief capers"
CostumedPlay.Community.ConventionCosplayers.Anime.Gundam,"Giant‑robot war dramas"
CostumedPlay.Community.ConventionCosplayers.Anime.FateStayNight,"Holy Grail wars"
CostumedPlay.Community.ConventionCosplayers.Anime.Ranma1_2,"Martial‑arts rom‑com"
CostumedPlay.Community.ConventionCosplayers.Anime.RurouniKenshin,"Meiji‑era swordsman"

/* ================ 2) MANGA (40 leaves) ============================ */
CostumedPlay.Community.ConventionCosplayers.Manga.VinlandSaga,"Viking epic"
CostumedPlay.Community.ConventionCosplayers.Manga.GoldenKamuy,"Treasure hunt in Hokkaido"
CostumedPlay.Community.ConventionCosplayers.Manga.20thCenturyBoys,"Apocalyptic cult thriller"
CostumedPlay.Community.ConventionCosplayers.Manga.Monster,"Psychological cat‑and‑mouse"
CostumedPlay.Community.ConventionCosplayers.Manga.Pluto,"Astro Boy reimagined"
CostumedPlay.Community.ConventionCosplayers.Manga.BillyBat,"Urasawa conspiracy bat"
CostumedPlay.Community.ConventionCosplayers.Manga.Kingdom,"Chinese warring‑states saga"
CostumedPlay.Community.ConventionCosplayers.Manga.SlamDunk,"Basketball classic"
CostumedPlay.Community.ConventionCosplayers.Manga.Yotsuba,"Curious slice‑of‑life"
CostumedPlay.Community.ConventionCosplayers.Manga.AstroBoy,"Tezuka robot classic"
CostumedPlay.Community.ConventionCosplayers.Manga.Phoenix,"Tezuka reincarnation epic"
CostumedPlay.Community.ConventionCosplayers.Manga.Dorohedoro,"Surreal magic & violence"
CostumedPlay.Community.ConventionCosplayers.Manga.Blame,"Cyberpunk labyrinth"
CostumedPlay.Community.ConventionCosplayers.Manga.Ajin,"Immortals reviving"
CostumedPlay.Community.ConventionCosplayers.Manga.Vagabond,"Musashi retelling"
CostumedPlay.Community.ConventionCosplayers.Manga.Basilisk,"Ninja feud"
CostumedPlay.Community.ConventionCosplayers.Manga.Baki,"Underground martial arts"
CostumedPlay.Community.ConventionCosplayers.Manga.Gantz,"Dead fight aliens"
CostumedPlay.Community.ConventionCosplayers.Manga.IAmAHero,"Paranoid zombie outbreak"
CostumedPlay.Community.ConventionCosplayers.Manga.Uzumaki,"Ito spiral horror"
CostumedPlay.Community.ConventionCosplayers.Manga.Tomie,"Ito immortal seductress"
CostumedPlay.Community.ConventionCosplayers.Manga.BattleAngelAlita,"Cyborg warrior future"
CostumedPlay.Community.ConventionCosplayers.Manga.Nana,"Two women, music & love"
CostumedPlay.Community.ConventionCosplayers.Manga.Orange,"Letters through time"
CostumedPlay.Community.ConventionCosplayers.Manga.HikaruNoGo,"Go‑playing ghost"
CostumedPlay.Community.ConventionCosplayers.Manga.Chihayafuru,"Karuta drama"
CostumedPlay.Community.ConventionCosplayers.Manga.Beck,"Rock band journey"
CostumedPlay.Community.ConventionCosplayers.Manga.SpaceBrothers,"Brothers aiming for space"
CostumedPlay.Community.ConventionCosplayers.Manga.YonaOfTheDawn,"Exiled princess & dragons"
CostumedPlay.Community.ConventionCosplayers.Manga.AkatsukiNoYona,"Alt title of above"
CostumedPlay.Community.ConventionCosplayers.Manga.Real,"Wheelchair basketball"
CostumedPlay.Community.ConventionCosplayers.Manga.BluePeriod,"Teen discovers art"
CostumedPlay.Community.ConventionCosplayers.Manga.Horimiya,"Secret‑identity romance"
CostumedPlay.Community.ConventionCosplayers.Manga.KomiCantCommunicate,"Social‑anxiety girl"
CostumedPlay.Community.ConventionCosplayers.Manga.SkullfaceBooksellerHondaSan,"Bookstore comedy"
CostumedPlay.Community.ConventionCosplayers.Manga.LaidBackCamp,"Cozy camping"
CostumedPlay.Community.ConventionCosplayers.Manga.BloomIntoYou,"F/F romance"
CostumedPlay.Community.ConventionCosplayers.Manga.Wotakoi,"Otaku office couple"
CostumedPlay.Community.ConventionCosplayers.Manga.MarchComesInLikeALion,"Shogi and depression"

/* ================ 3) VIDEO GAMES (40 leaves) ===================== */
CostumedPlay.Community.ConventionCosplayers.VideoGames.FinalFantasy,"Classic JRPG"
CostumedPlay.Community.ConventionCosplayers.VideoGames.KingdomHearts,"Disney + Square"
CostumedPlay.Community.ConventionCosplayers.VideoGames.TheLegendOfZelda,"Hyrule adventures"
CostumedPlay.Community.ConventionCosplayers.VideoGames.SuperMario,"Iconic plumber"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Metroid,"Samus Aran"
CostumedPlay.Community.ConventionCosplayers.VideoGames.FireEmblem,"Tactical permadeath"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Pokemon,"Pocket monsters"
CostumedPlay.Community.ConventionCosplayers.VideoGames.SonicTheHedgehog,"Fast blue hero"
CostumedPlay.Community.ConventionCosplayers.VideoGames.MegaMan,"Blue bomber"
CostumedPlay.Community.ConventionCosplayers.VideoGames.MonsterHunter,"Co‑op hunts"
CostumedPlay.Community.ConventionCosplayers.VideoGames.StreetFighter,"2D fighter"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Tekken,"3D fighter"
CostumedPlay.Community.ConventionCosplayers.VideoGames.SoulCalibur,"Weapon fighters"
CostumedPlay.Community.ConventionCosplayers.VideoGames.MortalKombat,"Fatalities"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Overwatch,"Hero shooter"
CostumedPlay.Community.ConventionCosplayers.VideoGames.LeagueOfLegends,"MOBA"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Dota2,"Valve MOBA"
CostumedPlay.Community.ConventionCosplayers.VideoGames.WorldOfWarcraft,"MMORPG"
CostumedPlay.Community.ConventionCosplayers.VideoGames.StarCraft,"RTS"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Diablo,"Demons ARPG"
CostumedPlay.Community.ConventionCosplayers.VideoGames.CallOfDuty,"Military FPS"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Battlefield,"Large‑scale FPS"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Halo,"Master Chief"
CostumedPlay.Community.ConventionCosplayers.VideoGames.GearsOfWar,"Locust battles"
CostumedPlay.Community.ConventionCosplayers.VideoGames.ApexLegends,"Battle royale"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Titanfall,"Pilots & mechs"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Fortnite,"BR with building"
CostumedPlay.Community.ConventionCosplayers.VideoGames.PUBG,"Realistic battle royale"
CostumedPlay.Community.ConventionCosplayers.VideoGames.CounterStrike,"T vs CT"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Valorant,"Tactical agents"
CostumedPlay.Community.ConventionCosplayers.VideoGames.TeamFortress2,"Class shooter"
CostumedPlay.Community.ConventionCosplayers.VideoGames.RocketLeague,"Soccer cars"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Roblox,"User worlds"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Minecraft,"Block sandbox"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Terraria,"2D crafting"
CostumedPlay.Community.ConventionCosplayers.VideoGames.AmongUs,"Social deduction"
CostumedPlay.Community.ConventionCosplayers.VideoGames.HollowKnight,"Bug metroidvania"
CostumedPlay.Community.ConventionCosplayers.VideoGames.Undertale,"Trope‑subverting RPG"
CostumedPlay.Community.ConventionCosplayers.VideoGames.EldenRing,"Open‑world dark fantasy"
CostumedPlay.Community.ConventionCosplayers.VideoGames.DarkSouls,"Hard fantasy"

/* ================ 4) COMICS (40 leaves) =========================== */
CostumedPlay.Community.ConventionCosplayers.Comics.Marvel,"Huge superhero universe"
CostumedPlay.Community.ConventionCosplayers.Comics.DCComics,"DC universe"
CostumedPlay.Community.ConventionCosplayers.Comics.SpiderMan,"Web‑slinger"
CostumedPlay.Community.ConventionCosplayers.Comics.XMen,"Mutant team"
CostumedPlay.Community.ConventionCosplayers.Comics.Batman,"Dark Knight"
CostumedPlay.Community.ConventionCosplayers.Comics.Superman,"Kryptonian hero"
CostumedPlay.Community.ConventionCosplayers.Comics.WonderWoman,"Amazonian warrior"
CostumedPlay.Community.ConventionCosplayers.Comics.GreenLantern,"Power ring"
CostumedPlay.Community.ConventionCosplayers.Comics.TheFlash,"Fastest man alive"
CostumedPlay.Community.ConventionCosplayers.Comics.Aquaman,"Atlantean king"
CostumedPlay.Community.ConventionCosplayers.Comics.IronMan,"Billionaire Avenger"
CostumedPlay.Community.ConventionCosplayers.Comics.CaptainAmerica,"Supersoldier"
CostumedPlay.Community.ConventionCosplayers.Comics.Thor,"Norse god"
CostumedPlay.Community.ConventionCosplayers.Comics.Hulk,"Gamma giant"
CostumedPlay.Community.ConventionCosplayers.Comics.BlackPanther,"Wakandan king"
CostumedPlay.Community.ConventionCosplayers.Comics.CaptainMarvel,"Cosmic hero"
CostumedPlay.Community.ConventionCosplayers.Comics.Hawkeye,"Archer Avenger"
CostumedPlay.Community.ConventionCosplayers.Comics.Wolverine,"Adamantium mutant"
CostumedPlay.Community.ConventionCosplayers.Comics.Deadpool,"Merc with a mouth"
CostumedPlay.Community.ConventionCosplayers.Comics.Venom,"Symbiote anti‑hero"
CostumedPlay.Community.ConventionCosplayers.Comics.ThePunisher,"Vigilante"
CostumedPlay.Community.ConventionCosplayers.Comics.Daredevil,"Blind lawyer hero"
CostumedPlay.Community.ConventionCosplayers.Comics.Joker,"Batman’s nemesis"
CostumedPlay.Community.ConventionCosplayers.Comics.HarleyQuinn,"Anti‑heroine clown"
CostumedPlay.Community.ConventionCosplayers.Comics.Cyborg,"Justice League member"
CostumedPlay.Community.ConventionCosplayers.Comics.Robin,"Batman’s sidekick"
CostumedPlay.Community.ConventionCosplayers.Comics.Batgirl,"Gotham heroine"
CostumedPlay.Community.ConventionCosplayers.Comics.Nightwing,"Grown‑up Robin"
CostumedPlay.Community.ConventionCosplayers.Comics.GreenArrow,"Bow vigilante"
CostumedPlay.Community.ConventionCosplayers.Comics.BlackCanary,"Sonic scream"
CostumedPlay.Community.ConventionCosplayers.Comics.Zatanna,"Spell magician"
CostumedPlay.Community.ConventionCosplayers.Comics.Constantine,"Occult detective"
CostumedPlay.Community.ConventionCosplayers.Comics.SwampThing,"Plant elemental"
CostumedPlay.Community.ConventionCosplayers.Comics.Hellboy,"Paranormal detective"
CostumedPlay.Community.ConventionCosplayers.Comics.Spawn,"Hellspawn anti‑hero"
CostumedPlay.Community.ConventionCosplayers.Comics.KickAss,"Homemade vigilantes"
CostumedPlay.Community.ConventionCosplayers.Comics.ScottPilgrim,"Fights evil exes"
CostumedPlay.Community.ConventionCosplayers.Comics.TheBoys,"Satirical supers"
CostumedPlay.Community.ConventionCosplayers.Comics.Invincible,"Teen superhero"
CostumedPlay.Community.ConventionCosplayers.Comics.UmbrellaAcademy,"Dysfunctional siblings"

/* ================ 5) SERIES (40 leaves) =========================== */
CostumedPlay.Community.ConventionCosplayers.Series.StarTrek,"Starship exploration"
CostumedPlay.Community.ConventionCosplayers.Series.GameOfThrones,"Dragons & intrigue"
CostumedPlay.Community.ConventionCosplayers.Series.TheWalkingDead,"Zombie apocalypse"
CostumedPlay.Community.ConventionCosplayers.Series.StrangerThings,"80s supernatural"
CostumedPlay.Community.ConventionCosplayers.Series.DoctorWho,"Time‑travel Doctor"
CostumedPlay.Community.ConventionCosplayers.Series.Sherlock,"Modern Holmes"
CostumedPlay.Community.ConventionCosplayers.Series.BuffyTheVampireSlayer,"Teen slayer"
CostumedPlay.Community.ConventionCosplayers.Series.Mandalorian,"Star Wars bounty hunter"
CostumedPlay.Community.ConventionCosplayers.Series.TheBoys,"Satire of supers"
CostumedPlay.Community.ConventionCosplayers.Series.Westworld,"Android sentience"
CostumedPlay.Community.ConventionCosplayers.Series.Farscape,"Astronaut lost in space"
CostumedPlay.Community.ConventionCosplayers.Series.Babylon5,"Space‑station diplomacy"
CostumedPlay.Community.ConventionCosplayers.Series.BattlestarGalactica,"Humans vs Cylons"
CostumedPlay.Community.ConventionCosplayers.Series.Firefly,"Cowboys in space"
CostumedPlay.Community.ConventionCosplayers.Series.TheExpanse,"Realistic solar system"
CostumedPlay.Community.ConventionCosplayers.Series.DowntonAbbey,"Edwardian drama"
CostumedPlay.Community.ConventionCosplayers.Series.BreakingBad,"Teacher‑turned kingpin"
CostumedPlay.Community.ConventionCosplayers.Series.BetterCallSaul,"Lawyer prequel"
CostumedPlay.Community.ConventionCosplayers.Series.TheFlash,"Speedster show"
CostumedPlay.Community.ConventionCosplayers.Series.Lucifer,"Fallen angel in LA"
CostumedPlay.Community.ConventionCosplayers.Series.Supernatural,"Brothers hunt monsters"
CostumedPlay.Community.ConventionCosplayers.Series.TeenWolf,"Modern werewolf drama"
CostumedPlay.Community.ConventionCosplayers.Series.VampireDiaries,"Vampire romance"
CostumedPlay.Community.ConventionCosplayers.Series.Riverdale,"Dark Archieverse"
CostumedPlay.Community.ConventionCosplayers.Series.ChillingAdventuresOfSabrina,"Occult Archieverse"
CostumedPlay.Community.ConventionCosplayers.Series.Smallville,"Young Superman"
CostumedPlay.Community.ConventionCosplayers.Series.HouseOfTheDragon,"Targaryen prequel"
CostumedPlay.Community.ConventionCosplayers.Series.FearTheWalkingDead,"TWD companion"
CostumedPlay.Community.ConventionCosplayers.Series.UmbrellaAcademy,"Dysfunctional supers"
CostumedPlay.Community.ConventionCosplayers.Series.AgentsOfSHIELD,"Marvel agency series"
CostumedPlay.Community.ConventionCosplayers.Series.Loki,"God of mischief"
CostumedPlay.Community.ConventionCosplayers.Series.WandaVision,"Reality‑warping sitcom"
CostumedPlay.Community.ConventionCosplayers.Series.Arrow,"Vigilante archer"
CostumedPlay.Community.ConventionCosplayers.Series.Supergirl,"Kryptonian heroine"
CostumedPlay.Community.ConventionCosplayers.Series.LegendsOfTomorrow,"Time‑travel misfits"
CostumedPlay.Community.ConventionCosplayers.Series.Lost,"Mystery island"
CostumedPlay.Community.ConventionCosplayers.Series.CarnivalRow,"Victorian fantasy"
CostumedPlay.Community.ConventionCosplayers.Series.WheelOfTime,"Epic fantasy adaptation"
CostumedPlay.Community.ConventionCosplayers.Series.Sandman,"Cosmic fantasy"
CostumedPlay.Community.ConventionCosplayers.Series.Wednesday,"Addams Family detective"

/* ================ 6) MOVIES (50 leaves) =========================== */
CostumedPlay.Community.ConventionCosplayers.Movies.StarWars,"Space‑opera saga"
CostumedPlay.Community.ConventionCosplayers.Movies.HarryPotter,"Wizards at Hogwarts"
CostumedPlay.Community.ConventionCosplayers.Movies.LordOfTheRings,"Middle‑earth epic"
CostumedPlay.Community.ConventionCosplayers.Movies.TheHobbit,"Bilbo & Smaug"
CostumedPlay.Community.ConventionCosplayers.Movies.ChroniclesOfNarnia,"Narnia realm"
CostumedPlay.Community.ConventionCosplayers.Movies.HungerGames,"Battle‑royale dystopia"
CostumedPlay.Community.ConventionCosplayers.Movies.Divergent,"Faction dystopia"
CostumedPlay.Community.ConventionCosplayers.Movies.TheMazeRunner,"Teens in maze"
CostumedPlay.Community.ConventionCosplayers.Movies.Twilight,"Vampire romance"
CostumedPlay.Community.ConventionCosplayers.Movies.Dune,"Politics on Arrakis"
CostumedPlay.Community.ConventionCosplayers.Movies.TheMatrix,"Simulation sci‑fi"
CostumedPlay.Community.ConventionCosplayers.Movies.JohnWick,"Relentless assassin"
CostumedPlay.Community.ConventionCosplayers.Movies.TheGodfather,"Mafia family saga"
CostumedPlay.Community.ConventionCosplayers.Movies.BackToTheFuture,"Time‑traveling DeLorean"
CostumedPlay.Community.ConventionCosplayers.Movies.IndianaJones,"Archaeologist adventurer"
CostumedPlay.Community.ConventionCosplayers.Movies.MenInBlack,"Agents vs aliens"
CostumedPlay.Community.ConventionCosplayers.Movies.RoboCop,"Cyborg cop"
CostumedPlay.Community.ConventionCosplayers.Movies.Terminator,"Time‑war cyborgs"
CostumedPlay.Community.ConventionCosplayers.Movies.Predator,"Alien hunter"
CostumedPlay.Community.ConventionCosplayers.Movies.DieHard,"NY cop in skyscraper"
CostumedPlay.Community.ConventionCosplayers.Movies.MadMax,"Post‑apocalyptic road"
CostumedPlay.Community.ConventionCosplayers.Movies.BladeRunner,"Replicant hunters"
CostumedPlay.Community.ConventionCosplayers.Movies.Tron,"Inside computer"
CostumedPlay.Community.ConventionCosplayers.Movies.ETTheExtraTerrestrial,"Friendly alien"
CostumedPlay.Community.ConventionCosplayers.Movies.Jaws,"Shark terror"
CostumedPlay.Community.ConventionCosplayers.Movies.JurassicPark,"Dinosaurs resurrected"
CostumedPlay.Community.ConventionCosplayers.Movies.PlanetOfTheApes,"Apes vs humans"
CostumedPlay.Community.ConventionCosplayers.Movies.TheFifthElement,"Cosmic elements"
CostumedPlay.Community.ConventionCosplayers.Movies.Armageddon,"Asteroid threat"
CostumedPlay.Community.ConventionCosplayers.Movies.TheDayAfterTomorrow,"Climate disaster"
CostumedPlay.Community.ConventionCosplayers.Movies.IndependenceDay,"Alien invasion"
CostumedPlay.Community.ConventionCosplayers.Movies.Titanic,"Ship disaster romance"
CostumedPlay.Community.ConventionCosplayers.Movies.AvatarFilm,"Humans vs Na'vi"
CostumedPlay.Community.ConventionCosplayers.Movies.PiratesOfTheCaribbean,"Swashbuckling pirates"
CostumedPlay.Community.ConventionCosplayers.Movies.JamesBond,"British spy saga"
CostumedPlay.Community.ConventionCosplayers.Movies.MissionImpossible,"Spy missions"
CostumedPlay.Community.ConventionCosplayers.Movies.TheKingsman,"Stylish spies"
CostumedPlay.Community.ConventionCosplayers.Movies.ScottPilgrim,"Fights evil exes"
CostumedPlay.Community.ConventionCosplayers.Movies.KickAss,"Homemade vigilantes"
CostumedPlay.Community.ConventionCosplayers.Movies.PacificRim,"Jaegers vs Kaiju"
CostumedPlay.Community.ConventionCosplayers.Movies.WillyWonka,"Chocolate factory"
CostumedPlay.Community.ConventionCosplayers.Movies.WizardOfOz,"Classic fantasy"
CostumedPlay.Community.ConventionCosplayers.Movies.Ghostbusters,"NYC ghost team"
CostumedPlay.Community.ConventionCosplayers.Movies.Aliens,"Xenomorph sequel"
CostumedPlay.Community.ConventionCosplayers.Movies.Godzilla,"Kaiju lizard"
CostumedPlay.Community.ConventionCosplayers.Movies.KingKong,"Giant ape"
CostumedPlay.Community.ConventionCosplayers.Movies.Rocky,"Underdog boxer"
`.trim();
